services:
  postgres:
    image: postgres:17-alpine
    container_name: opsmind-postgres-inv
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IS1234567
      POSTGRES_DB: opsmind_assets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opsmind-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8.0
    container_name: opsmind-mongodb-inv
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: opsmind_assets
    volumes:
      - mongodb_data:/data/db
    networks:
      - opsmind-net
    restart: unless-stopped

  opsmind-rabbitmq:
    image: rabbitmq:3-management
    container_name: opsmind-rabbitmq-inv
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=opsmind
      - RABBITMQ_DEFAULT_PASS=opsmind
    networks:
      - opsmind-net

  inventory-backend:
    build: .
    container_name: opsmind-inventory-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=opsmind-local-jwt
      - DATABASE_URL=postgresql://postgres:IS1234567@postgres:5432/opsmind_assets
      - RABBITMQ_URI=amqp://opsmind:opsmind@opsmind-rabbitmq:5672
    depends_on:
      - postgres
      - opsmind-rabbitmq
    networks:
      - opsmind-net
     
    inventory-backend-worker:
    build: .
    container_name: opsmind-inventory-backend-worker
    restart: always
    command: ["npm", "run", "worker"]

networks:
  opsmind-net:
    external: true

volumes:
  postgres_data:
  mongodb_data:
