services:
  opsmind-frontend:
    container_name: opsmind-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:85"
    environment:
      # If your backend runs on the same Docker network, you can point the UI to it
      # Example: http://tickets-service:8080/api
      OPSMIND_API_URL: ${OPSMIND_API_URL:-http://localhost:3002}
      OPSMIND_TICKET_URL: ${OPSMIND_TICKET_URL:-http://localhost:3001}
      OPSMIND_WORKFLOW_API_URL: ${OPSMIND_WORKFLOW_API_URL:-http://localhost:3003}
      OPSMIND_AI_API_URL: ${OPSMIND_AI_API_URL:-http://localhost:8000}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      GEMINI_API_URL: ${GEMINI_API_URL:-https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent}
      NODE_ENV: production
      PORT: 80
    networks:
      - opsmind-net

networks:
  opsmind-net:
    name: opsmind-net
    driver: bridge
    external: true
