services:
  opsmind-agentic-ai-service:
    container_name: opsmind-agentic-ai-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4010:4010"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 4010
      SERVICE_NAME: opsmind-agentic-ai-service
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: gemma3:4b
      DATABASE_URL: mysql://opsmind:opsmind@mysql:3306/agentic_ai_db
    networks:
      - opsmind-net
    restart: unless-stopped

networks:
  opsmind-net:
    external: true
