import { TelemetrySourceDefinition } from './types';

export const TELEMETRY_SOURCE_REGISTRY: TelemetrySourceDefinition[] = [
  {
    sourceKey: 'manual_toggle',
    displayName: 'Manual Toggle',
    supportedAssetTypes: ['*'],
    mode: 'manual',
    trustLevel: 'low',
    freshnessThresholdMinutes: 10080,
    expectedSignals: ['telemetryEnabled', 'liveSignalReceived'],
    requiredFields: ['telemetryEnabled'],
    statusMappingStrategy: 'toggle_seed_status',
    consumptionMappingStrategy: 'none',
    qualityImpactMappingStrategy: 'none',
    confidenceRules: ['enabled_without_signal=0.25', 'disabled=0.1'],
    failureBehavior: 'mark_not_monitored',
    examplePayload: {
      telemetryEnabled: true,
      liveSignalReceived: false,
    },
  },
  {
    sourceKey: 'manual_inspection',
    displayName: 'Manual Inspection',
    supportedAssetTypes: ['*'],
    mode: 'manual',
    trustLevel: 'medium',
    freshnessThresholdMinutes: 43200,
    expectedSignals: ['inspectionScore', 'condition', 'inspector'],
    requiredFields: ['inspectionScore'],
    statusMappingStrategy: 'condition_based',
    consumptionMappingStrategy: 'inspection_decay',
    qualityImpactMappingStrategy: 'inspection_quality_impact',
    confidenceRules: ['recent_inspection<=90_days=0.7', 'stale_inspection=0.4'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      inspectionScore: 0.78,
      condition: 'fair',
      inspector: 'inventory_admin',
    },
  },
  {
    sourceKey: 'device_agent',
    displayName: 'Device Agent',
    supportedAssetTypes: ['laptop', 'desktop', 'tablet', 'server', 'projector', 'smartboard', 'camera', 'speaker'],
    mode: 'push',
    trustLevel: 'high',
    freshnessThresholdMinutes: 15,
    expectedSignals: ['heartbeat', 'activeUser', 'activeMinutes', 'idleMinutes', 'cpu', 'ram', 'disk'],
    requiredFields: ['heartbeat'],
    statusMappingStrategy: 'heartbeat_plus_activity',
    consumptionMappingStrategy: 'active_vs_idle_ratio',
    qualityImpactMappingStrategy: 'thermal_and_health_correlation',
    confidenceRules: ['fresh_heartbeat=0.9', 'stale_heartbeat=0.3'],
    failureBehavior: 'keep_last_with_decay',
    examplePayload: {
      heartbeat: '2026-05-22T10:30:00Z',
      activeUser: 'user123',
      activeMinutes: 54,
      idleMinutes: 6,
      cpu: 0.61,
      ram: 0.74,
      disk: 0.48,
    },
  },
  {
    sourceKey: 'ping',
    displayName: 'Network Ping',
    supportedAssetTypes: ['laptop', 'desktop', 'server', 'router', 'switch', 'access_point', 'firewall', 'printer', 'scanner'],
    mode: 'poll',
    trustLevel: 'medium',
    freshnessThresholdMinutes: 5,
    expectedSignals: ['reachable', 'rttMs', 'packetLoss'],
    requiredFields: ['reachable'],
    statusMappingStrategy: 'reachability_only',
    consumptionMappingStrategy: 'none',
    qualityImpactMappingStrategy: 'connectivity_risk',
    confidenceRules: ['reachable=true=0.7', 'reachable=false=0.6'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      reachable: true,
      rttMs: 11,
      packetLoss: 0.0,
    },
  },
  {
    sourceKey: 'snmp',
    displayName: 'SNMP',
    supportedAssetTypes: ['router', 'switch', 'access_point', 'firewall', 'printer', 'scanner', 'server'],
    mode: 'poll',
    trustLevel: 'high',
    freshnessThresholdMinutes: 10,
    expectedSignals: ['uptimeSeconds', 'interfaceErrors', 'throughput', 'temperature', 'faults'],
    requiredFields: ['uptimeSeconds'],
    statusMappingStrategy: 'uptime_and_health',
    consumptionMappingStrategy: 'throughput_and_error_intensity',
    qualityImpactMappingStrategy: 'error_fault_pressure',
    confidenceRules: ['uptime_present=0.88', 'missing_core_oid=0.45'],
    failureBehavior: 'keep_last_with_decay',
    examplePayload: {
      uptimeSeconds: 954321,
      interfaceErrors: 3,
      throughputMbps: 320,
      temperatureC: 54,
    },
  },
  {
    sourceKey: 'mdm',
    displayName: 'MDM',
    supportedAssetTypes: ['laptop', 'tablet'],
    mode: 'poll',
    trustLevel: 'high',
    freshnessThresholdMinutes: 60,
    expectedSignals: ['mdmOnline', 'lastSeen', 'batteryCycles', 'appUsageMinutes'],
    requiredFields: ['mdmOnline', 'lastSeen'],
    statusMappingStrategy: 'device_presence_and_usage',
    consumptionMappingStrategy: 'battery_cycle_pressure',
    qualityImpactMappingStrategy: 'battery_health_impact',
    confidenceRules: ['managed_and_seen_recently=0.85', 'seen_stale=0.4'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      mdmOnline: true,
      lastSeen: '2026-05-22T10:25:00Z',
      batteryCycles: 421,
      appUsageMinutes: 212,
    },
  },
  {
    sourceKey: 'printer_counter',
    displayName: 'Printer Counter',
    supportedAssetTypes: ['printer', 'scanner'],
    mode: 'poll',
    trustLevel: 'high',
    freshnessThresholdMinutes: 120,
    expectedSignals: ['pageCount', 'scanCount', 'tonerLevel', 'jamCount', 'errorState'],
    requiredFields: ['pageCount'],
    statusMappingStrategy: 'counter_delta_and_error_state',
    consumptionMappingStrategy: 'volume_and_fault_rate',
    qualityImpactMappingStrategy: 'consumable_and_jam_pressure',
    confidenceRules: ['counter_growth=0.82', 'counter_static_without_error=0.5'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      pageCount: 182340,
      tonerLevel: 0.42,
      jamCount: 3,
      errorState: 'none',
    },
  },
  {
    sourceKey: 'network_controller',
    displayName: 'Network Controller',
    supportedAssetTypes: ['router', 'switch', 'access_point', 'firewall'],
    mode: 'poll',
    trustLevel: 'high',
    freshnessThresholdMinutes: 15,
    expectedSignals: ['controllerSeen', 'clientsConnected', 'throughput', 'retryRate'],
    requiredFields: ['controllerSeen'],
    statusMappingStrategy: 'controller_presence_and_load',
    consumptionMappingStrategy: 'client_load_intensity',
    qualityImpactMappingStrategy: 'error_retry_pressure',
    confidenceRules: ['controller_seen=true=0.9', 'controller_seen=false=0.35'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      controllerSeen: true,
      clientsConnected: 44,
      throughputMbps: 138,
      retryRate: 0.02,
    },
  },
  {
    sourceKey: 'maintenance_system',
    displayName: 'Maintenance System',
    supportedAssetTypes: ['*'],
    mode: 'derived',
    trustLevel: 'medium',
    freshnessThresholdMinutes: 10080,
    expectedSignals: ['serviceIntervalBreach', 'repairCount', 'faultEvents', 'downtimeHours'],
    requiredFields: ['repairCount'],
    statusMappingStrategy: 'maintenance_condition_proxy',
    consumptionMappingStrategy: 'repair_and_downtime_intensity',
    qualityImpactMappingStrategy: 'service_breach_impact',
    confidenceRules: ['structured_maintenance_feed=0.75', 'sparse_records=0.4'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      repairCount: 4,
      faultEvents: 7,
      downtimeHours: 32,
      serviceIntervalBreach: true,
    },
  },
  {
    sourceKey: 'ticket_history',
    displayName: 'Ticket History',
    supportedAssetTypes: ['*'],
    mode: 'derived',
    trustLevel: 'medium',
    freshnessThresholdMinutes: 1440,
    expectedSignals: ['incidentCount', 'severityWeightedCount', 'recencyDays'],
    requiredFields: ['incidentCount'],
    statusMappingStrategy: 'incident_pressure_proxy',
    consumptionMappingStrategy: 'incident_frequency',
    qualityImpactMappingStrategy: 'severity_weighted_quality_drop',
    confidenceRules: ['recent_structured_tickets=0.68', 'old_sparse_tickets=0.35'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      incidentCount: 6,
      severityWeightedCount: 9.5,
      recencyDays: 14,
    },
  },
  {
    sourceKey: 'vendor_api',
    displayName: 'Vendor API',
    supportedAssetTypes: ['*'],
    mode: 'poll',
    trustLevel: 'medium',
    freshnessThresholdMinutes: 10080,
    expectedSignals: ['warrantyStatus', 'healthFlags', 'bulletins'],
    requiredFields: ['warrantyStatus'],
    statusMappingStrategy: 'vendor_health_proxy',
    consumptionMappingStrategy: 'none',
    qualityImpactMappingStrategy: 'vendor_health_flags',
    confidenceRules: ['signed_vendor_response=0.78', 'partial_response=0.45'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      warrantyStatus: 'active',
      healthFlags: ['none'],
      bulletins: [],
    },
  },
  {
    sourceKey: 'building_management_system',
    displayName: 'Building Management System',
    supportedAssetTypes: ['generator', 'hvac'],
    mode: 'poll',
    trustLevel: 'high',
    freshnessThresholdMinutes: 30,
    expectedSignals: ['runtimeHours', 'load', 'temperature', 'faults', 'serviceDue'],
    requiredFields: ['runtimeHours'],
    statusMappingStrategy: 'runtime_and_fault_model',
    consumptionMappingStrategy: 'runtime_load_severity',
    qualityImpactMappingStrategy: 'fault_and_service_due_impact',
    confidenceRules: ['fresh_runtime_feed=0.88', 'missing_fault_channel=0.55'],
    failureBehavior: 'mark_insufficient_data',
    examplePayload: {
      runtimeHours: 4832,
      load: 0.63,
      temperatureC: 47,
      faults: 0,
      serviceDue: false,
    },
  },
];

const REGISTRY_BY_KEY = TELEMETRY_SOURCE_REGISTRY.reduce((acc, source) => {
  acc[source.sourceKey] = source;
  return acc;
}, {} as Record<string, TelemetrySourceDefinition>);

export function getTelemetrySourceDefinition(sourceKey: string): TelemetrySourceDefinition | null {
  return REGISTRY_BY_KEY[String(sourceKey || '').trim()] || null;
}

export function listTelemetrySources(): TelemetrySourceDefinition[] {
  return TELEMETRY_SOURCE_REGISTRY;
}
