version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: reporting-mongo
    ports:
       - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - opsmind-net
    restart: unless-stopped

  reporting-service:
    build: .
    container_name: reporting-service
    ports:
      - "3004:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - opsmind-net
    restart: unless-stopped

networks:
  opsmind-net:
    external: true   

volumes:
  mongo_data: