version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: reporting-mongo
    ports:
       - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - opsmind-net
    restart: unless-stopped

  reporting-service:
    build: .
    container_name: reporting-service
    ports:
      - "3006:3000"
    environment:
      PORT: "3000"
      MONGO_URI: mongodb://mongo:27017/reporting
      TICKET_SERVICE_URL: http://ticket-service:3000
      AUTH_SERVICE_URL: http://auth-service:3002
      REPORT_SYNC_URL: http://127.0.0.1:3000/analytics/sync
    depends_on:
      - mongo
    networks:
      - opsmind-net
    restart: unless-stopped

networks:
  opsmind-net:
    external: true   

volumes:
  mongo_data:
