-- This migration is intentionally empty.
--
-- The original migration tried to alter TicketAssignmentHistory and
-- TicketStatusHistory before those tables were created by the later
-- 20260508000000_add_ticket_history migration. That breaks clean
-- `prisma migrate deploy` runs. The current Prisma schema already matches
-- the tables created by 20260508000000_add_ticket_history, so there is no
-- deployable SQL needed here.
